image:
  repository: ghcr.io/teruelplan/plantogether-destination-service
  tag: latest

service:
  port: 8083

grpc:
  enabled: true
  port: 9083

ingress:
  path: /api/v1/trips

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
